spring.application.name=post


logging.file.name=logs/app.log
logging.file.path=logs
server.port=8085
logging.level.com.microblog.post=DEBUG
logging.level.com.microblog.post.feign.UserDbClient= DEBUG
 
spring.cloud.openfeign.client.config.db-service.loggerLevel= full
spring.cloud.openfeign.client.config.default.loggerLevel=full