spring.application.name=login-signup

server.port=9090


logging.file.name=logs/app.log
logging.file.path=logs


logging.level.com.microblog.login_signup=DEBUG
logging.level.com.microblog.login_signup.feign.UserDbClient= DEBUG

spring.cloud.openfeign.client.config.db-service.loggerLevel= full
spring.cloud.openfeign.client.config.default.loggerLevel=full